example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wishlist.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import add_barang_json, show_ajax_wishlist, show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user 
from wishlist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax_wishlist, name='show_ajax_wishlist'),
    path('ajax/submit', add_barang_json, name='add_barang_json'),
    
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse


# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Amira Nisrina',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_ajax_wishlist(request):
    context = {
    'nama': 'Amira Nisrina',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def add_barang_json(request):
    if request.method == 'POST':
        nama_barang = request.POST['nama_barang']
        harga_barang = request.POST['harga_barang']
        deskripsi = request.POST['deskripsi']
        buat_barang = BarangWishlist.objects.create(
            nama_barang=nama_barang, 
            harga_barang=harga_barang, 
            deskripsi=deskripsi
        )
        return JsonResponse(
            {
                'error':False,
                'msg':'Success'
            }
        )
    return redirect('wishlist:show_ajax_wishlist')


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
      

<body style="background-color:#feffff ;">
    <!-- Navbar -->
    <nav class="navbar navbar-dark" style="background-color:#0D3B66; padding: 8px; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
        <!-- Container wrapper -->
        <div class="container-fluid">
    
        <!-- Navbar brand -->
        <a class="navbar-brand" href="#" style="color:#feffff; font-weight: 500;">Amira Nisrina</a>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'wishlist:logout' %}" style="color:#feffff; font-weight: 500;"><span class="glyphicon glyphicon-log-out" style="color:#feffff" ></span> Log Out</a></li>
        </ul>

        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <table class="table table-hover" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; color: #0D3B66; ">
        <thead class="thead-dark" style="background-color:#C9E1F8; font-size: 16px; color: black; ">
        <tr>
            <th style="text-align:center;">Nama Barang</th>
            <th style="text-align:center;">Harga Barang</th>
            <th style="text-align:center;">Deskripsi</th>
        </tr>
        </thead>
        <tbody>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</body>

</html>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript">

        function getDataFromForm($form) {
            var unindexed_items = $form.serializeArray();
            var result = {};
            $.map(unindexed_items, function (n, i) {
                result[n['name']] = n['value'];
            });
            return result;
        }

        $(document).ready(function () {
            $.getJSON("{% url 'wishlist:show_json' %}", function (json) {
                var table = [];
                $.each(json, function (index, data) {
                    var row = [];
                    var fields = data.fields
                    row.push("<td>" + data.fields.nama_barang + "</td>");
                    row.push("<td>" + data.fields.harga_barang + "</td>");
                    row.push("<td>" + data.fields.deskripsi + "</td>");
                    table.push("<tr>" + row.join("") + "</tr>");
                });
                document.getElementById("display").innerHTML = table.join("");
            });

            $("#tambah_barang_form").submit(function (e) {
                e.preventDefault();
                var $form = $(this);
                var serializedData = getDataFromForm($form);
                console.log(serializedData)
                $.ajax({
                    url: "{% url 'wishlist:add_barang_json' %}",
                    type: "POST",
                    data: serializedData,
                    dataType: 'text',
                    success: function (data) {
                        $.getJSON(
                            "{% url 'wishlist:show_json' %}",
                            function (json) {
                                var table = [];
                                $.each(json, function (index, data) {
                                    var row = [];
                                    var fields = data.fields
                                    row.push("<td>" + data.fields.nama_barang + "</td>");
                                    row.push("<td>" + data.fields.harga_barang + "</td>");
                                    row.push("<td>" + data.fields.deskripsi + "</td>");
                                    table.push("<tr>" + row.join("") + "</tr>");
                                });
                                document.getElementById("display").innerHTML = table.join("");
                            });
                    }
                });
            });
        });

    </script>
</head>
      

<body style="background-color:#feffff ;">
    <!-- Navbar -->
    <nav class="navbar navbar-dark" style="background-color:#0D3B66; padding: 8px; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
        <!-- Container wrapper -->
        <div class="container-fluid">
    
        <!-- Navbar brand -->
        <a class="navbar-brand" href="#" style="color:#feffff; font-weight: 500;">Amira Nisrina</a>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'wishlist:logout' %}" style="color:#feffff; font-weight: 500;"><span class="glyphicon glyphicon-log-out" style="color:#feffff" ></span> Log Out</a></li>
        </ul>

        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <form class="container" method="POST" name="barang_form" id="tambah_barang_form">
        {% csrf_token %}
        <fieldset>
            <legend>Tambah Barang Wishlist</legend>
            <input class="form-control mb-3" type="text" placeholder="Nama barang" name="nama_barang">
            <input class="form-control mb-3" type="number" min="1" step="any" placeholder="Harga barang"
                name="harga_barang">
            <textarea class="form-control mb-3" rows="3" placeholder="Deskripsi" name="deskripsi"></textarea>
            <button type="submit" class="btn btn-primary btnClick">Submit</button>
        </fieldset>
    </form>

    <table class="table table-hover" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; color: #0D3B66; margin: 15px; ">
        <thead class="thead-dark" style="background-color:#C9E1F8; font-size: 16px; color: black; ">
            <tr>
                <th style="text-align:center;">Nama Barang</th>
                <th style="text-align:center;">Harga Barang</th>
                <th style="text-align:center;">Deskripsi</th>
            </tr>
        </thead>
        <tbody id="display">
        
        </tbody>
        
  
     
    </table>
    <h5>Sesi terakhir login: {{ last_login }}</h5>
</body>

</html>

{% endblock content %}